#!/bin/bash
mkdir build
cp editor_new build
cd build
cython editor_new --embed
PYTHONLIBVER=python$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')$(python3-config --abiflags)
gcc -Os $(python3-config --includes) editor_new.c -o ctk_EDITOR $(python3-config --ldflags) -l$PYTHONLIBVER
